<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="test1"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="3.302">
  <properties />
            <testcase name="LoginTest01" time="3.302" classname="com.myfirstproject.LoginTest">
                <failure type="junit.framework.AssertionFailedError"
                  message="元素识别异常，退出此次用例"
              >
<![CDATA[junit.framework.AssertionFailedError: 元素识别异常，退出此次用例
  junit.framework.Assert.fail(Assert.java:47)
  com.myfirstuiframework.WebElementUtils.getElement(WebElementUtils.java:56)
  com.myfirstuiframework.WebElementUtils$1.apply(WebElementUtils.java:65)
  com.myfirstuiframework.WebElementUtils$1.apply(WebElementUtils.java:1)
  org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:238)
  com.myfirstuiframework.WebElementUtils.findElement(WebElementUtils.java:63)
  com.myfirstuiframework.WebElementUtils.input(WebElementUtils.java:78)
  com.myfirstpages.LoginPage.inputUserInfo(LoginPage.java:23)
  com.myfirstproject.LoginTest.LoginTest01(LoginTest.java:31)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  org.testng.TestRunner.privateRun(TestRunner.java:756)
  org.testng.TestRunner.run(TestRunner.java:610)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
  org.testng.TestNG.runSuites(TestNG.java:1133)
  org.testng.TestNG.run(TestNG.java:1104)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
      </failure>

          </testcase>
  
  
  
</testsuite>
