<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.myfirstproject.loginTest" tests="1" time="24.423" ignored="4" failures="0" timestamp="11 六月 2018 03:37:07 GMT" skipped="0" hostname="denglifu_PC" errors="1">
  <testcase name="f01" time="24.423" classname="com.myfirstproject.loginTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.myfirstuiframework.WebElementUtils.getLocator(WebElementUtils.java:123)
	at com.myfirstpages.MainPage.<init>(MainPage.java:16)
	at com.myfirstactions.clickLoginButton.loginSucess(clickLoginButton.java:32)
	at com.myfirstactions.clickMenuProject.clickProjectLoginTest(clickMenuProject.java:33)
	at com.myfirstproject.loginTest.f01(loginTest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- f01 -->
  <testcase name="f05" classname="com.myfirstproject.loginTest">
    <skipped/>
  </testcase> <!-- f05 -->
  <testcase name="f03" classname="com.myfirstproject.loginTest">
    <skipped/>
  </testcase> <!-- f03 -->
  <testcase name="f04" classname="com.myfirstproject.loginTest">
    <skipped/>
  </testcase> <!-- f04 -->
  <testcase name="f02" classname="com.myfirstproject.loginTest">
    <skipped/>
  </testcase> <!-- f02 -->
</testsuite> <!-- com.myfirstproject.loginTest -->
